eval: False
features: 'spec'

model_path: ''

save_trained_name: 'best_model_ASVSpoof2019.pth'
model_folder: 'checkpoints/residualnet_model'

batch_size: 64 #128
num_epochs: 100
early_stopping: 10
lr: 0.00001
track: 'logical'
is_eval: False
eval_part: 0

cache_dir: 'data/features/'
mfcc_features: 'data/features/mfcc'
spec_features: 'data/features/spec'

df_train_path: 'data/df_train.csv'
df_dev_path: 'data/df_dev.csv'
df_eval_path: 'data/df_eval.csv'
df_aug_path: 'data/df_aug.csv'

fsamp: 16000
win_len: 3
hop_size: 3

eval_batch_size: 64 #128
model_path_spec: './checkpoints/residualnet_model/model_spec_100_64_1e-05/best_model_ASVSpoof2019.pth'
#'./checkpoints/residualnet_model/model_spec_100_64_1e-05/best_model_ASV_LIBRI.pth'
