features: 'spec'

save_trained_name: 'best_model_ASVSpoof2019_v0.pth'
model_folder_pow: 'checkpoints/SENet_model_v0'
model_folder_mag: 'checkpoints/SENet_model_mag'

batch_size: 64
num_epochs: 100
early_stopping: 10
lr: 0.00001
track: 'logical'
is_eval: False
eval_part: 0

cache_dir: 'data/features'
spec_features: 'data/features/spec'

df_train_path: 'data/df_train.csv'
df_dev_path: 'data/df_dev.csv'
df_eval_path: 'data/df_eval_19.csv'
df_eval_path_3s: 'data/df_eval_19_3s.csv'

fsamp: 16000
win_len: 3
hop_size: 3

eval_batch_size: 64
model_path_spec_pow_v0: 'checkpoints/SENet_model_v0/model_spec_100_64_1e-05_v0/best_model_ASVSpoof2019_v0.pth'
model_path_spec_mag: 'checkpoints/SENet_model_mag/model_spec_100_64_1e-05_mag/best_model_ASVSpoof2019_mag.pth'